spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  application:
    name: surplus360-backend
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        enable_lazy_load_no_trans: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080}
  
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
  
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}
  
  websocket:
    allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
  
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.surplus360: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey}
    expiration: ${JWT_EXPIRATION:86400000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
  
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,PATCH,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:*}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
  
  file-upload:
    base-path: ${FILE_UPLOAD_BASE_PATH:./uploads}
    max-size: ${FILE_UPLOAD_MAX_SIZE:50MB}
    allowed-types: ${FILE_UPLOAD_ALLOWED_TYPES:image/jpeg,image/png,image/gif,image/webp,application/pdf}
  
  notification:
    email:
      enabled: ${NOTIFICATION_EMAIL_ENABLED:true}
      from: ${NOTIFICATION_EMAIL_FROM:noreply@surplus360.com}
    websocket:
      enabled: ${NOTIFICATION_WEBSOCKET_ENABLED:true}
  
  elasticsearch:
    index-prefix: ${ELASTICSEARCH_INDEX_PREFIX:surplus360}
    refresh-interval: ${ELASTICSEARCH_REFRESH_INTERVAL:30s}
  
  rse:
    calculation:
      co2-factor: ${RSE_CO2_FACTOR:0.5}
      waste-factor: ${RSE_WASTE_FACTOR:0.8}
  
  analytics:
    enabled: ${ANALYTICS_ENABLED:true}
    retention-days: ${ANALYTICS_RETENTION_DAYS:365}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json