spring:
  application:
    name: surplus-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/surplus_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: surplus_user
    password: surplus_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope: email,profile
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  cache:
    type: simple
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

logging:
  level:
    com.surplus: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

application:
  jwt:
    secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890}
    token-validity-in-seconds: 86400 # 24 hours
    token-validity-in-seconds-for-remember-me: 2592000 # 30 days
  
  cors:
    allowed-origins: 
      - http://localhost:3000
      - http://localhost:5173
      - https://yourdomain.com
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600
  
  security:
    authentication:
      jwt:
        secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890}
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  
  mail:
    from: noreply@surplus.com
    base-url: http://localhost:3000
  
  file:
    upload-dir: ./uploads
    max-file-size: 10MB
    allowed-extensions: jpg,jpeg,png,gif,pdf,doc,docx

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method